"use client";

import { motion } from "framer-motion";
import { useLanguageStore } from "@/lib/store";
import { translations } from "@/lib/translations";
import { 
  Users, 
  ArrowRight, 
  BarChart3, 
  ShieldCheck, 
  Zap, 
  Share2, 
  Database, 
  Globe,
  Lock,
  Search,
  Layout,
  Briefcase,
  FileText,
  Target
} from "lucide-react";
import Link from "next/link";

export default function NgosSolutionPage() {
  const { lang } = useLanguageStore();
  const t = translations[lang as keyof typeof translations];

  const pageTranslations = {
    id: {
        ngoTitle: "Advokasi Berbasis Bukti",
        ngoSub: "Berikan NGO Anda kekuatan data terverifikasi untuk memengaruhi kebijakan publik secara efektif dan kredibel.",
        campaignTitle: "Analitik Kampanye Terpadu",
        camp1Title: "Visualisasi Dampak",
        camp1Desc: "Tunjukkan kepada donatur hasil nyata dari upaya advokasi Anda dengan data on-chain.",
        camp2Title: "Evidence Vault",
        camp2Desc: "Simpan laporan lapangan dan data akar rumput dalam brankas digital terenkripsi.",
        camp3Title: "Lobbying Presisi",
        camp3Desc: "Gunakan data sentimen skala besar untuk meyakinkan pembuat kebijakan.",
        influenceTitle: "Peta Pengaruh Kebijakan",
        influenceDesc: "Dlibration memungkinkan NGO melacak bagaimana masukan data mereka memengaruhi draf kebijakan yang dihasilkan oleh AI pemerintah.",
        point1: "Pelacakan Masukan Data",
        point2: "Laporan Dampak Otomatis",
        point3: "Verifikasi Donor Transparan",
        collaborationTitle: "Kolaborasi Global NGO",
        collaborationDesc: "Hubungkan NGO Anda dengan jaringan advokasi global yang menggunakan standar data Dlibration.",
    },
    en: {
        ngoTitle: "Evidence-Based Advocacy",
        ngoSub: "Give your NGO the power of verified data to influence public policy effectively and credibly.",
        campaignTitle: "Unified Campaign Analytics",
        camp1Title: "Impact Visualization",
        camp1Desc: "Show donors the real results of your advocacy efforts with on-chain data.",
        camp2Title: "Evidence Vault",
        camp2Desc: "Store field reports and grassroots data in an encrypted digital vault.",
        camp3Title: "Precision Lobbying",
        camp3Desc: "Use large-scale sentiment data to convince policymakers.",
        influenceTitle: "Policy Influence Map",
        influenceDesc: "Dlibration allows NGOs to track how their data inputs influence policy drafts generated by government AI.",
        point1: "Data Input Tracking",
        point2: "Automated Impact Reports",
        point3: "Transparent Donor Verification",
        collaborationTitle: "Global NGO Collaboration",
        collaborationDesc: "Connect your NGO with a global advocacy network using Dlibration data standards.",
    }
  };

  const pt = pageTranslations[lang as keyof typeof pageTranslations];

  return (
    <div className="bg-background min-h-screen pt-48 pb-40 relative overflow-hidden">
      <div className="bg-pattern-grid absolute inset-0 opacity-10 -z-10"></div>
      
      <div className="max-w-7xl mx-auto px-6">
        
        {/* 1. HERO SECTION */}
        <div className="grid lg:grid-cols-2 gap-24 items-center mb-48">
            <motion.div
                initial={{ opacity: 0, x: -30 }}
                animate={{ opacity: 1, x: 0 }}
            >
                <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-vault-amber/30 bg-vault-amber/5 text-vault-amber font-black text-[10px] tracking-[0.2em] uppercase mb-8">
                    <Briefcase size={14} /> Civil Society Empowerment
                </div>
                <h1 className="text-6xl md:text-8xl font-black text-foreground mb-8 tracking-tighter leading-[0.9] uppercase">
                    Advocacy <br/> 
                    <span className="text-vault-amber">Evolved.</span>
                </h1>
                <p className="text-xl text-muted-foreground mb-12 leading-relaxed max-w-xl font-medium">
                    {lang === 'id' 
                      ? "Ubah narasi menjadi data yang tidak bisa dibantah. Dlibration membantu NGO menjembatani kesenjangan antara fakta di lapangan dan kebijakan di meja birokrasi."
                      : "Turn narratives into incontrovertible data. Dlibration helps NGOs bridge the gap between field facts and bureaucratic policy tables."}
                </p>
                <div className="flex flex-wrap gap-6">
                    <Link href="/contact" className="bg-white text-black px-10 py-5 rounded-2xl font-black flex items-center gap-3 hover:bg-vault-amber transition-all shadow-2xl">
                        {lang === 'id' ? "Daftar Paket NGO" : "Get NGO Pack"} <ArrowRight size={22} />
                    </Link>
                </div>
            </motion.div>

            <motion.div 
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                className="relative"
            >
                <div className="bg-vault-card border border-white/10 p-2 rounded-[4rem] shadow-2xl relative overflow-hidden group">
                    <div className="bg-[#0a0a0a] rounded-[3.5rem] p-16 relative overflow-hidden flex flex-col items-center">
                        <div className="bg-pattern-diagonal absolute inset-0 opacity-5"></div>
                        <div className="relative z-10 text-center">
                            <Target size={120} className="text-vault-amber/20 mb-8 mx-auto animate-pulse" />
                            <h3 className="text-2xl font-black text-foreground mb-4 uppercase tracking-tighter">Advocacy Engine</h3>
                            <div className="space-y-4 w-full">
                                <div className="h-2 w-full bg-white/5 rounded-full"></div>
                                <div className="h-2 w-3/4 bg-white/5 rounded-full mx-auto"></div>
                            </div>
                            <div className="mt-12 p-6 bg-vault-amber/10 border border-vault-amber/20 rounded-2xl font-mono text-[10px] text-vault-amber">
                                {`STATUS: CAMPAIGN_ACTIVE`} <br/>
                                {`IMPACT_SCORE: 8.4/10`}
                            </div>
                        </div>
                    </div>
                </div>
            </motion.div>
        </div>

        {/* 2. CAMPAIGN ANALYTICS SECTION */}
        <section className="mb-48">
            <h2 className="text-4xl md:text-6xl font-black text-foreground mb-24 tracking-tighter text-center uppercase">{pt.campaignTitle}</h2>
            <div className="grid md:grid-cols-3 gap-8">
                {[
                    { title: pt.camp1Title, desc: pt.camp1Desc, icon: <Share2 />, color: "text-blue-400" },
                    { title: pt.camp2Title, desc: pt.camp2Desc, icon: <Lock />, color: "text-vault-amber" },
                    { title: pt.camp3Title, desc: pt.camp3Desc, icon: <Zap />, color: "text-green-400" }
                ].map((item, i) => (
                    <motion.div 
                        key={i}
                        whileHover={{ y: -10 }}
                        className="p-12 bg-white/2 border border-white/10 rounded-[3rem] group"
                    >
                        <div className={`${item.color} mb-8 transition-transform group-hover:scale-110`}>
                            {item.icon}
                        </div>
                        <h3 className="text-2xl font-black text-foreground mb-6 uppercase tracking-tight leading-none">{item.title}</h3>
                        <p className="text-muted-foreground font-medium leading-relaxed">{item.desc}</p>
                    </motion.div>
                ))}
            </div>
        </section>

        {/* 3. POLICY INFLUENCE MAP SECTION */}
        <section className="mb-48 bg-white/[0.02] border border-white/10 rounded-[4rem] p-16 lg:p-24 overflow-hidden relative">
            <div className="absolute top-0 left-0 w-[500px] h-[500px] bg-vault-amber/5 blur-[100px] -z-10"></div>
            <div className="grid lg:grid-cols-2 gap-24 items-center">
                <div className="relative order-2 lg:order-1">
                    <div className="bg-vault-card border border-white/10 rounded-3xl p-10">
                        <div className="flex items-center gap-4 mb-8">
                            <div className="w-12 h-12 bg-vault-amber rounded-full flex items-center justify-center text-black">
                                <FileText size={24} />
                            </div>
                            <div className="h-[2px] w-12 bg-white/10"></div>
                            <div className="w-12 h-12 bg-blue-500 rounded-full flex items-center justify-center text-white">
                                <Search size={24} />
                            </div>
                        </div>
                        <div className="space-y-4">
                            <div className="h-4 w-full bg-white/5 rounded-full"></div>
                            <div className="h-4 w-2/3 bg-white/5 rounded-full"></div>
                        </div>
                    </div>
                </div>
                <div className="order-1 lg:order-2">
                    <h2 className="text-4xl md:text-6xl font-black text-foreground mb-12 tracking-tighter leading-none uppercase">{pt.influenceTitle}</h2>
                    <p className="text-xl text-muted-foreground mb-12 font-medium leading-relaxed">{pt.influenceDesc}</p>
                    <div className="space-y-6">
                        {[pt.point1, pt.point2, pt.point3].map((point, i) => (
                            <div key={i} className="flex items-center gap-4 text-foreground font-bold">
                                <div className="w-10 h-10 bg-vault-amber/10 rounded-xl flex items-center justify-center text-vault-amber shrink-0">
                                    <BarChart3 size={20} />
                                </div>
                                {point}
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </section>

        {/* 4. GLOBAL COLLABORATION */}
        <section className="mb-48 text-center max-w-4xl mx-auto">
            <Globe className="text-vault-amber mx-auto mb-10 animate-spin-slow" size={80} />
            <h2 className="text-4xl md:text-6xl font-black text-foreground mb-8 tracking-tighter uppercase">{pt.collaborationTitle}</h2>
            <p className="text-xl text-muted-foreground font-medium leading-relaxed mb-12">
                {pt.collaborationDesc}
            </p>
            <div className="flex flex-wrap justify-center gap-6">
                {['Global Data Standards', 'NGO Resource Sharing', 'Cross-Border Advocacy', 'Verified Impact Network'].map(tag => (
                    <div key={tag} className="px-8 py-3 bg-white/5 border border-white/10 rounded-full text-xs font-black uppercase tracking-widest text-muted-foreground">
                        {tag}
                    </div>
                ))}
            </div>
        </section>

        {/* 5. CALL TO ACTION */}
        <section className="p-20 bg-vault-amber border border-white/10 rounded-[5rem] text-center relative overflow-hidden group">
             <div className="bg-pattern-diagonal absolute inset-0 opacity-10"></div>
             <div className="relative z-10 max-w-4xl mx-auto">
                <Users size={80} className="text-black mx-auto mb-12 animate-float opacity-30" />
                <h2 className="text-4xl md:text-7xl font-black text-black mb-8 tracking-tighter leading-[0.9] uppercase">
                    Amplify your <br/> Impact.
                </h2>
                <p className="text-xl text-black/80 mb-12 font-bold leading-relaxed">
                    Stop guessing. Start knowing. Dlibration gives your NGO the evidentiary power it needs to change the world.
                </p>
                <Link href="/contact" className="bg-black text-white px-16 py-8 rounded-[2.5rem] font-black text-2xl transition-all hover:scale-105 shadow-2xl inline-flex items-center gap-4">
                   Partner with Us <ArrowRight size={28} />
                </Link>
             </div>
        </section>

      </div>
    </div>
  );
}
