"use client";

import { motion } from "framer-motion";
import { useLanguageStore } from "@/lib/store";
import { translations } from "@/lib/translations";
import { 
  Users, 
  ArrowRight, 
  BarChart3, 
  ShieldCheck, 
  Zap, 
  Share2, 
  Database, 
  Globe,
  Lock,
  Search,
  Layout,
  Briefcase,
  FileText,
  Target,
  Sparkles
} from "lucide-react";
import Link from "next/link";

export default function NgosSolutionPage() {
  const { lang } = useLanguageStore();
  const t = translations[lang as keyof typeof translations];

  const pageTranslations = {
    id: {
        ngoTitle: "Advokasi Berbasis Bukti",
        ngoSub: "Berikan NGO Anda kekuatan data terverifikasi untuk memengaruhi kebijakan publik secara efektif dan kredibel.",
        campaignTitle: "Analitik Kampanye Terpadu",
        camp1Title: "Visualisasi Dampak",
        camp1Desc: "Tunjukkan kepada donatur hasil nyata dari upaya advokasi Anda dengan data on-chain.",
        camp2Title: "Evidence Vault",
        camp2Desc: "Simpan laporan lapangan dan data akar rumput dalam brankas digital terenkripsi.",
        camp3Title: "Lobbying Presisi",
        camp3Desc: "Gunakan data sentimen skala besar untuk meyakinkan pembuat kebijakan.",
        influenceTitle: "Peta Pengaruh Kebijakan",
        influenceDesc: "Dlibration memungkinkan NGO melacak bagaimana masukan data mereka memengaruhi draf kebijakan yang dihasilkan oleh AI pemerintah.",
        point1: "Pelacakan Masukan Data",
        point2: "Laporan Dampak Otomatis",
        point3: "Verifikasi Donor Transparan",
        collaborationTitle: "Kolaborasi Global NGO",
        collaborationDesc: "Hubungkan NGO Anda dengan jaringan advokasi global yang menggunakan standar data Dlibration.",
    },
    en: {
        ngoTitle: "Evidence-Based Advocacy",
        ngoSub: "Give your NGO the power of verified data to influence public policy effectively and credibly.",
        campaignTitle: "Unified Campaign Analytics",
        camp1Title: "Impact Visualization",
        camp1Desc: "Show donors the real results of your advocacy efforts with on-chain data.",
        camp2Title: "Evidence Vault",
        camp2Desc: "Store field reports and grassroots data in an encrypted digital vault.",
        camp3Title: "Precision Lobbying",
        camp3Desc: "Use large-scale sentiment data to convince policymakers.",
        influenceTitle: "Policy Influence Map",
        influenceDesc: "Dlibration allows NGOs to track how their data inputs influence policy drafts generated by government AI.",
        point1: "Data Input Tracking",
        point2: "Automated Impact Reports",
        point3: "Transparent Donor Verification",
        collaborationTitle: "Global NGO Collaboration",
        collaborationDesc: "Connect your NGO with a global advocacy network using Dlibration data standards.",
    }
  };

  const pt = pageTranslations[lang as keyof typeof pageTranslations];

  return (
    <div className="bg-background min-h-screen pt-48 pb-40 relative overflow-hidden text-foreground">
      <div className="bg-pattern-grid absolute inset-0 opacity-10 -z-10"></div>
      
      <div className="max-w-7xl mx-auto px-6">
        
        {/* 1. HERO SECTION */}
        <div className="grid lg:grid-cols-2 gap-24 items-center mb-48">
            <motion.div
                initial={{ opacity: 0, x: -30 }}
                animate={{ opacity: 1, x: 0 }}
            >
                <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-vault-amber/30 bg-vault-amber/5 text-vault-amber font-black text-[10px] tracking-[0.2em] uppercase mb-8 shadow-sm">
                    <Briefcase size={14} /> Civil Society Empowerment
                </div>
                <h1 className="text-6xl md:text-8xl font-black text-foreground mb-8 tracking-tighter leading-[0.9] uppercase">
                    Advocacy <br/> 
                    <span className="text-vault-amber">Evolved.</span>
                </h1>
                <p className="text-xl text-muted-foreground mb-12 leading-relaxed max-w-xl font-medium">
                    {lang === 'id' 
                      ? "Ubah narasi menjadi data yang tidak bisa dibantah. Dlibration membantu NGO menjembatani kesenjangan antara fakta di lapangan dan kebijakan di meja birokrasi."
                      : "Turn narratives into incontrovertible data. Dlibration helps NGOs bridge the gap between field facts and bureaucratic policy tables."}
                </p>
                <div className="flex flex-wrap gap-6">
                    <Link href="/contact" className="bg-foreground text-background px-12 py-6 rounded-2xl font-black flex items-center gap-3 hover:bg-vault-amber hover:text-black transition-all shadow-2xl uppercase text-sm tracking-widest active:scale-95">
                        {lang === 'id' ? "Daftar Paket NGO" : "Get NGO Pack"} <ArrowRight size={22} />
                    </Link>
                </div>
            </motion.div>

            <motion.div 
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                className="relative"
            >
                <div className="absolute -inset-10 bg-vault-amber/10 blur-[120px] rounded-full -z-10 animate-pulse"></div>
                <div className="bg-muted border border-border p-4 rounded-[4rem] shadow-2xl relative overflow-hidden group hover:rotate-1 transition-transform duration-700">
                    <div className="bg-background rounded-[3.5rem] p-16 relative overflow-hidden flex flex-col items-center border border-border shadow-inner text-center">
                        <div className="bg-pattern-diagonal absolute inset-0 opacity-5"></div>
                        <div className="relative z-10 w-full">
                            <Target size={140} className="text-vault-amber/10 mb-10 mx-auto animate-pulse" />
                            <h3 className="text-3xl font-black text-foreground mb-4 uppercase tracking-tighter leading-none">Advocacy Engine</h3>
                            <div className="space-y-6 w-full max-w-xs mx-auto mb-12">
                                <div className="h-2.5 w-full bg-muted rounded-full overflow-hidden">
                                    <div className="h-full w-4/5 bg-vault-amber"></div>
                                </div>
                                <div className="h-2.5 w-3/4 bg-muted rounded-full mx-auto overflow-hidden">
                                    <div className="h-full w-2/3 bg-blue-500"></div>
                                </div>
                            </div>
                            <div className="p-8 bg-muted border border-border rounded-3xl font-mono text-[10px] text-vault-amber flex items-center justify-between shadow-sm">
                                <div className="text-left">
                                    <div className="opacity-40 uppercase tracking-widest mb-1">Status</div>
                                    <div className="font-black">CAMPAIGN_ACTIVE</div>
                                </div>
                                <div className="text-right">
                                    <div className="opacity-40 uppercase tracking-widest mb-1">Impact</div>
                                    <div className="font-black text-lg">8.4/10</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </motion.div>
        </div>

        {/* 2. CAMPAIGN ANALYTICS SECTION */}
        <section className="mb-48">
            <h2 className="text-4xl md:text-7xl font-black text-foreground mb-24 tracking-tighter text-center uppercase leading-none">{pt.campaignTitle}</h2>
            <div className="grid md:grid-cols-3 gap-10">
                {[
                    { title: pt.camp1Title, desc: pt.camp1Desc, icon: <Share2 />, color: "text-blue-500" },
                    { title: pt.camp2Title, desc: pt.camp2Desc, icon: <Lock />, color: "text-vault-amber" },
                    { title: pt.camp3Title, desc: pt.camp3Desc, icon: <Zap />, color: "text-green-500" }
                ].map((item, i) => (
                    <motion.div 
                        key={i}
                        whileHover={{ y: -10 }}
                        className="p-16 bg-muted/50 border border-border rounded-[4rem] group shadow-sm hover:border-vault-amber/30 transition-all"
                    >
                        <div className={`${item.color} mb-10 transition-transform group-hover:scale-110 bg-background w-24 h-24 flex items-center justify-center rounded-[2rem] border border-border shadow-inner`}>
                            {item.icon}
                        </div>
                        <h3 className="text-2xl font-black text-foreground mb-6 uppercase tracking-tight leading-none">{item.title}</h3>
                        <p className="text-muted-foreground font-medium leading-relaxed">{item.desc}</p>
                    </motion.div>
                ))}
            </div>
        </section>

        {/* 3. POLICY INFLUENCE MAP SECTION */}
        <section className="mb-48 bg-muted/50 border border-border rounded-[5rem] p-16 lg:p-32 overflow-hidden relative shadow-inner">
            <div className="absolute top-0 left-0 w-[600px] h-[600px] bg-vault-amber/5 blur-[150px] -z-10"></div>
            <div className="grid lg:grid-cols-2 gap-32 items-center">
                <div className="relative order-2 lg:order-1">
                    <div className="bg-background border border-border rounded-[4rem] p-12 shadow-2xl relative group">
                        <div className="absolute inset-0 bg-pattern-diagonal opacity-5"></div>
                        <div className="flex items-center gap-6 mb-12">
                            <div className="w-16 h-16 bg-vault-amber/10 rounded-[1.5rem] flex items-center justify-center text-vault-amber border border-vault-amber/20 shadow-sm">
                                <FileText size={32} />
                            </div>
                            <div className="h-[2px] w-20 bg-border relative">
                                <div className="absolute top-1/2 -translate-y-1/2 left-0 w-2 h-2 bg-vault-amber rounded-full"></div>
                                <div className="absolute top-1/2 -translate-y-1/2 right-0 w-2 h-2 bg-blue-500 rounded-full animate-ping"></div>
                            </div>
                            <div className="w-16 h-16 bg-blue-500/10 rounded-[1.5rem] flex items-center justify-center text-blue-500 border border-blue-500/20 shadow-sm">
                                <Search size={32} />
                            </div>
                        </div>
                        <div className="space-y-6">
                            <div className="h-3 w-full bg-muted rounded-full overflow-hidden">
                                <div className="h-full w-4/5 bg-vault-amber/20"></div>
                            </div>
                            <div className="h-3 w-2/3 bg-muted rounded-full overflow-hidden">
                                <div className="h-full w-1/2 bg-blue-500/20"></div>
                            </div>
                            <div className="h-3 w-3/4 bg-muted rounded-full overflow-hidden">
                                <div className="h-full w-1/3 bg-green-500/20"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="order-1 lg:order-2">
                    <h2 className="text-4xl md:text-7xl font-black text-foreground mb-12 tracking-tighter leading-none uppercase">{pt.influenceTitle}</h2>
                    <p className="text-xl text-muted-foreground mb-12 font-medium leading-relaxed italic">{pt.influenceDesc}</p>
                    <div className="space-y-10">
                        {[pt.point1, pt.point2, pt.point3].map((point, i) => (
                            <div key={i} className="flex items-center gap-6 text-foreground font-black uppercase text-xs tracking-[0.2em]">
                                <div className="w-14 h-14 bg-vault-amber/10 rounded-2xl flex items-center justify-center text-vault-amber shrink-0 border border-vault-amber/20 shadow-sm">
                                    <BarChart3 size={28} />
                                </div>
                                {point}
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </section>

        {/* 4. GLOBAL COLLABORATION */}
        <section className="mb-48 text-center max-w-5xl mx-auto">
            <div className="w-24 h-24 bg-muted border border-border rounded-[2rem] flex items-center justify-center mx-auto mb-12 shadow-inner group hover:scale-110 transition-transform">
                <Globe className="text-vault-amber animate-spin-slow" size={56} />
            </div>
            <h2 className="text-4xl md:text-8xl font-black text-foreground mb-10 tracking-tighter uppercase leading-none">{pt.collaborationTitle}</h2>
            <p className="text-xl md:text-2xl text-muted-foreground font-medium leading-relaxed mb-16 italic max-w-4xl mx-auto">
                {pt.collaborationDesc}
            </p>
            <div className="flex flex-wrap justify-center gap-8">
                {['Global Data Standards', 'NGO Resource Sharing', 'Cross-Border Advocacy', 'Verified Impact Network'].map(tag => (
                    <div key={tag} className="px-12 py-5 bg-muted border border-border rounded-[2rem] text-[10px] font-black uppercase tracking-[0.4em] text-muted-foreground hover:border-vault-amber hover:text-foreground transition-all cursor-default shadow-sm active:scale-95">
                        {tag}
                    </div>
                ))}
            </div>
        </section>

        {/* 5. CALL TO ACTION */}
        <section className="p-20 md:p-32 bg-vault-amber border border-vault-amber/30 rounded-[6rem] text-center relative overflow-hidden group shadow-2xl">
             <div className="bg-pattern-diagonal absolute inset-0 opacity-20"></div>
             <div className="relative z-10 max-w-5xl mx-auto">
                <div className="w-24 h-24 bg-black rounded-3xl flex items-center justify-center mx-auto mb-16 shadow-2xl group-hover:rotate-12 transition-transform duration-500">
                    <Sparkles size={48} className="text-white opacity-40 animate-pulse" />
                </div>
                <h2 className="text-5xl md:text-8xl font-black text-black mb-10 tracking-tighter leading-[0.85] uppercase">
                    Amplify your <br/> Impact.
                </h2>
                <p className="text-2xl text-black/70 mb-16 font-black leading-relaxed max-w-4xl mx-auto uppercase italic tracking-tight">
                    Stop guessing. Start knowing. Dlibration gives your NGO the evidentiary power it needs to change the world.
                </p>
                <Link href="/contact" className="bg-black text-white px-20 py-10 rounded-[3rem] font-black text-3xl transition-all hover:scale-105 shadow-2xl inline-flex items-center gap-6 active:scale-95 group/btn overflow-hidden relative">
                   <span className="relative z-10">Partner with Us Now</span> <ArrowRight size={36} className="relative z-10 group-hover/btn:translate-x-3 transition-transform" />
                   <div className="absolute inset-0 bg-white/10 translate-y-full group-hover/btn:translate-y-0 transition-transform duration-500"></div>
                </Link>
             </div>
        </section>

      </div>
    </div>
  );
}
